import "server-only";
import { eq } from "drizzle-orm";
import { db } from "@/db";
import { files } from "@/db/schema";

// File storage for proof, claim photos and tracker exports. Stored in Postgres (the files table), so a
// deploy needs nothing but DATABASE_URL. Keys are always generated by us (deals/{dealId}/…), never taken
// from the client. Photos are compressed on the phone first; uploads are capped (see MAX_UPLOAD_BYTES).

export async function putObject(key: string, bytes: Uint8Array, contentType?: string) {
  // Insert only: a key is never overwritten (the primary key refuses a second write, a trigger refuses updates).
  await db.insert(files).values({ key, bytes: Buffer.from(bytes), contentType: contentType ?? null, sizeBytes: bytes.byteLength });
}

export async function getObject(key: string): Promise<Buffer | null> {
  const [row] = await db.select({ bytes: files.bytes }).from(files).where(eq(files.key, key));
  return row?.bytes ?? null;
}

/** Only for removing a mistaken upload before proof is locked. */
export async function deleteObject(key: string) {
  await db.delete(files).where(eq(files.key, key));
}

/** Safe file name part for a key: letters, digits, dot, dash, underscore. */
export function safeName(name: string) {
  const cleaned = name.normalize("NFKD").replace(/[^\w.-]+/g, "-").replace(/-+/g, "-").slice(-80);
  return cleaned || "file";
}
