import "server-only";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

// File storage for proof and claim photos. Local disk for now (./storage, gitignored).
// Swap for an R2/S3 driver behind the same three functions before deploying: Vercel's disk isn't persistent.
// Keys are always generated by us (deals/{dealId}/{itemId}-{name}), never taken from the client.

// Paths are resolved at runtime (turbopackIgnore below keeps the bundler from tracing the whole project).
const ROOT = path.resolve(/*turbopackIgnore: true*/ process.env.STORAGE_DIR ?? "storage");

function resolveKey(key: string) {
  const full = path.resolve(ROOT, key);
  if (!full.startsWith(ROOT + path.sep)) throw new Error("invalid storage key");
  return full;
}

export async function putObject(key: string, bytes: Uint8Array) {
  const full = resolveKey(key);
  await mkdir(/*turbopackIgnore: true*/ path.dirname(full), { recursive: true });
  // "wx": fail rather than overwrite — every upload gets a new key.
  await writeFile(/*turbopackIgnore: true*/ full, bytes, { flag: "wx" });
}

export async function getObject(key: string): Promise<Buffer | null> {
  try {
    return await readFile(/*turbopackIgnore: true*/ resolveKey(key));
  } catch {
    return null;
  }
}

/** Only for removing a mistaken upload before proof is locked. */
export async function deleteObject(key: string) {
  await rm(/*turbopackIgnore: true*/ resolveKey(key), { force: true });
}

/** Safe file name part for a key: letters, digits, dot, dash, underscore. */
export function safeName(name: string) {
  const cleaned = name.normalize("NFKD").replace(/[^\w.-]+/g, "-").replace(/-+/g, "-").slice(-80);
  return cleaned || "file";
}
